// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
  DISCORD_CLIENT_ID: '1305913184204623964';
  DISCORD_CLIENT_SECRET: string;
  DISCORD_REDIRECT_URI: string;
  SUCCESS_URL: string;
  COOKIE_DOMAIN: string;
}
