name = "mamoru-auth"
main = "src/app.ts"
compatibility_date = "2024-12-05"

[vars]
DISCORD_CLIENT_ID="1305913184204623964" # or provide your own

[[ kv_namespaces ]]
binding = "tokens"
id = "83128358-3fb8-457a-afac-7a7cf7cb8a24"

[[ kv_namespaces ]]
binding = "states"
id = "171163db-0a72-48bc-97f5-b0f731a03c11"

[observability]
enabled = true
head_sampling_rate = 1