name = "mamoru-auth"
main = "src/app.ts"
compatibility_date = "2024-12-05"

[vars]
DISCORD_CLIENT_ID="1305913184204623964" # or provide your own

[[ kv_namespaces ]]
binding = "tokens"
id = "40b7e9d19a0344d5b994c5c785228fed"

[[ kv_namespaces ]]
binding = "states"
id = "1875b126281a45919b4bea0d8eaf7f7d"

[observability]
enabled = true
head_sampling_rate = 1