// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

export interface Env {
	states: KVNamespace;
	users: KVNamespace;
	persist: KVNamespace;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_REDIRECT_URI: string;
	APP_URL: string;
}
