// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

type Env = {
  tokens: KVNamespace;
  states: KVNamespace;
  index: KVNamespace;
  DISCORD_CLIENT_SECRET: string;
  DISCORD_CLIENT_ID: string;
  DISCORD_REDIRECT_URI: string;
  CLIENT_URL: string;
};
