name = "mamoru-auth"
main = "src/app.ts"
compatibility_date = "2024-12-05"

[[ kv_namespaces ]]
binding = "states"
id = "28521ed8b5874ee1b99c83fee9a2b7ce"

[[ kv_namespaces ]]
binding = "users"
id = "e576988b-cf3d-46b5-a9ae-16806ede0fd8"

[[ kv_namespaces ]]
binding = "persist"
id = "fe5def91-aca4-4ca7-bf77-f03224631520"

[observability]
enabled = true
head_sampling_rate = 1