// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

type Env = {
  DISCORD_CLIENT_ID: '1305913184204623964';
  DISCORD_PUBLIC_KEY: '94d76e3ac693a41b27eaa7a83e19fb54416e74cb96331a2e31c801162d46fc27';
  DISCORD_BOT_TOKEN: string;
};
